spring:
  application:
    name: eot-a
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: ${PORT:8080}

app:
  greetings: "Request sent: %s (%s) -> %s"

---

spring:
  config:
    activate:
      on-cloud-platform: kubernetes
    import: configserver:http://eot-config-server:8080
